name: Testing Configuration Variables

on: workflow_dispatch

env:
    cloud: google-cloud

jobs:
    greeting_job:
      runs-on: tenki-standard-medium-4c-8g
      env:
          Greeting: Hello
      steps:
          - name: "Say Hello AW it's Tuesday"
            run: echo "$Greeting $First_Name is using $cloud with project ID ${{ vars.PROJECT_ID }}"
            env:
             First_Name: Abdul