name: Testing Context Variables

on: workflow_dispatch

env:
  cloud: google-cloud

jobs:
  test_context_variables_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Checking Context Variables"
        run: |
          echo "Repository Name: ${{ github.repository }}"
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Actor or Triggered By: ${{ github.actor }}"
