name: Testing Secret Variables

on: workflow_dispatch
env:
  ACTIONS_STEP_DEBUG: true
jobs:
  test_context_variables:
    runs-on: tenki-standard-medium-4c-8g
    steps:
      - name: "Checking Secret Variable"
        run: |
          echo "Secret Value : ${{ secrets.MY_KEY }}"